[package]
name = "nukleus"
author = "Skuld Norniern"
version = "0.1.0"
repository = "https://github.com/Nukleus-Language/nukleus"
description = "New AI, GUI, Cross-Platform Programming language"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1"
pest_derive = "2.1"
cfg-if = "0.1"
anyhow = "1.0"
#cranelift = "0.76.0"
#cranelift-module = "0.76.0"
#cranelift-jit = "0.76.0"
#inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }
colored = "1.6"

[lib]
crate-type = ["cdylib", "rlib"]

