[package]
name = "nk-lexer"
authors = ["Skuld Norniern <skuldnorniern@gmail.com>"]
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
nk-diagnostics = { path = "../nk-diagnostics" }

[lints.clippy]
unwrap_used = "deny"
cognitive_complexity = "deny"
result_large_err = "allow"