[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inksac = "0.2.0"
# lexer = { path = "../nk-lexer" }
astgen = { path = "../nk-astgen" }
